sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t bibhups/react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true bibhups/react-app npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "react-frontend-app"
  env: "Reactfrontendapp-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-519126177525"
  bucket_path: "react-frontend-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
